# Generated by Django 5.2.11 on 2026-07-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_feedback_user_feedback_result_excel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spatialjoinresult",
            name="change_shapefile",
            field=models.FileField(blank=True, null=True, upload_to="shapefiles/"),
        ),
        migrations.AlterField(
            model_name="spatialjoinresult",
            name="main_shapefile",
            field=models.FileField(blank=True, null=True, upload_to="shapefiles/"),
        ),
        migrations.AlterField(
            model_name="spatialjoinresult",
            name="result_excel",
            field=models.FileField(blank=True, null=True, upload_to="output/"),
        ),
        migrations.AlterField(
            model_name="spatialjoinresult",
            name="result_shapefile",
            field=models.FileField(blank=True, null=True, upload_to="output/"),
        ),
    ]
